# Generated by Django 4.0.3 on 2022-04-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_message_userfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msgText',
            field=models.CharField(max_length=500),
        ),
    ]
